# Generated by Django 3.1.3 on 2020-11-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.IntegerField(default=2),
        ),
    ]
