# Generated by Django 3.1.3 on 2020-11-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='value',
            new_name='number',
        ),
    ]
