# Generated by Django 3.1.3 on 2020-11-12 04:44

from django.db import migrations
from django.core.management import call_command

def run_reset_data(apps, schema_editor):
    call_command('reset_data')

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201112_0434'),
    ]

    operations = [
        migrations.RunPython(run_reset_data)
    ]
